{
 "title": "Spark Application",
 "tags": [ "spark" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Name",
    "query": "label_values(spark_app_info,application_name)"
   },
   {
    "name": "executor",
    "query": "label_values(spark_executor_info{application_name=\"$Name\", executor_id!=\"driver\"}, executor_id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "spark_app_info{application_name=\"$Name\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Running time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_app_duration_seconds{application_name=\"$Name\"}"
    }
   ]
  },
  {
   "title": "Executor Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_executor_count{application_name=\"$Name\"} - 1"
    }
   ]
  },
  {
   "title": "Total Cores Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_executor_cores_total{application_name=\"$Name\", executor_id!=\"driver\"})"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Executors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_info{application_name=\"$Name\", active=\"true\", blacklisted=\"false\", executor_id!=\"driver\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(spark_executor_info{application_name=\"$Name\", active=\"false\", blacklisted=\"false\", executor_id!=\"driver\"})",
     "legendFormat": "Removed"
    },
    {
     "expr": "sum(spark_executor_info{application_name=\"$Name\", blacklisted=\"true\", executor_id!=\"driver\"})",
     "legendFormat": "Blacklisted"
    }
   ]
  },
  {
   "title": "Failed Tasks Last 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (executor_id) (\n  irate(spark_executor_tasks_failed_total{application_name=\"$Name\", executor_id!=\"driver\"}[5m])\n)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Tasks Last 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (executor_id) (\n   irate(spark_executor_tasks_total{application_name=\"$Name\", executor_id!=\"driver\"}[5m])\n)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_tasks_active_count{application_name=\"$Name\", executor_id!=\"driver\"}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Completed Tasks Last 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (executor_id) (\n  irate(spark_executor_tasks_completed_total{application_name=\"$Name\", executor_id!=\"driver\"}[5m])\n)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  { "title": "Executor: $executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "executor" },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "spark_executor_info{application_name=\"$Name\", executor_id=\"$executor\", active=\"true\"} or on() vector(0)"
    }
   ]
  },
  {
   "title": "Cores Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_executor_cores_total{application_name=\"$Name\", executor_id=\"$executor\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "spark_executor_memory_used_bytes{application_name=\"$Name\", executor_id=\"$executor\"} / spark_executor_memory_bytes_max{application_name=\"$Name\", executor_id=\"$executor\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 }, "content": "\n\n" },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_executor_tasks_active_count{application_name=\"$Name\", executor_id=\"$executor\"} ",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Tasks Last 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(spark_executor_tasks_total{application_name=\"$Name\", executor_id=\"$executor\"}[5m])",
     "legendFormat": "Tasks"
    },
    {
     "expr": "irate(spark_executor_tasks_completed_total{application_name=\"$Name\", executor_id=\"$executor\"}[5m])",
     "legendFormat": "Completed"
    },
    {
     "expr": "irate(spark_executor_tasks_failed_total{application_name=\"$Name\", executor_id=\"$executor\"}[5m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Total input bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_input_bytes_total{application_name=\"$Name\", executor_id=\"$executor\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle read / write total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_shuffle_read_bytes_total{application_name=\"$Name\", executor_id=\"$executor\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(spark_executor_shuffle_write_bytes_total{application_name=\"$Name\", executor_id=\"$executor\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "GC Time 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(spark_executor_gc_time_total_milliseconds{application_name=\"$Name\", executor_id=\"$executor\"}[5m])",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_memory_used_bytes{application_name=\"$Name\", executor_id=\"$executor\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_disk_used_bytes{application_name=\"$Name\", executor_id=\"$executor\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  }
 ]
}