{
 "title": "Wave Cluster",
 "tags": [ "spark" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Cluster Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "topk(1, kube_node_info)", "legendFormat": "{{kubelet_version}}" }
   ]
  },
  {
   "title": "Region",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, kubelet_node_name)",
     "legendFormat": "{{topology_kubernetes_io_region}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "App Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_app_info) or on() vector(0)"
    }
   ]
  },
  {
   "title": "App Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(spark_app_duration_seconds)"
    }
   ]
  },
  {
   "title": "Spark Apps",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(spark_app_info) by (application_name)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Spark versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (version) (\n  spark_app_info\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Job Running time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(spark_app_duration_seconds) by (application_name)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  { "title": "Node information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "Node Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_node_name) by (node_lifecycle)",
     "legendFormat": "{{node_lifecycle}}"
    }
   ]
  },
  {
   "title": "Node Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_node_name) by (topology_kubernetes_io_zone, node_kubernetes_io_instance_type)",
     "legendFormat": "{{topology_kubernetes_io_zone}}, {{node_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"user\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(sum(node_memory_MemAvailable_bytes) by (kubernetes_node) * 100 / sum(node_memory_MemTotal_bytes) by (kubernetes_node))"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 5, "y": 36 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_SwapCached_bytes",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}