# permissions for end users to view wavecomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavecomponent-viewer-role
rules:
- apiGroups:
  - wave.spot.io
  resources:
  - wavecomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wave.spot.io
  resources:
  - wavecomponents/status
  verbs:
  - get
