# permissions for end users to edit wavecomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wavecomponent-editor-role
rules:
- apiGroups:
  - wave.spot.io
  resources:
  - wavecomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wave.spot.io
  resources:
  - wavecomponents/status
  verbs:
  - get
