// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spotinst/wave-operator/internal/spot/client (interfaces: AWSClient)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	gomock "github.com/golang/mock/gomock"
	client "github.com/spotinst/wave-operator/internal/spot/client"
	reflect "reflect"
)

// MockAWSClient is a mock of AWSClient interface
type MockAWSClient struct {
	ctrl     *gomock.Controller
	recorder *MockAWSClientMockRecorder
}

// MockAWSClientMockRecorder is the mock recorder for MockAWSClient
type MockAWSClientMockRecorder struct {
	mock *MockAWSClient
}

// NewMockAWSClient creates a new mock instance
func NewMockAWSClient(ctrl *gomock.Controller) *MockAWSClient {
	mock := &MockAWSClient{ctrl: ctrl}
	mock.recorder = &MockAWSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAWSClient) EXPECT() *MockAWSClientMockRecorder {
	return m.recorder
}

// GetAvailableInstanceTypesInRegion mocks base method
func (m *MockAWSClient) GetAvailableInstanceTypesInRegion(arg0 string) ([]*client.InstanceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableInstanceTypesInRegion", arg0)
	ret0, _ := ret[0].([]*client.InstanceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableInstanceTypesInRegion indicates an expected call of GetAvailableInstanceTypesInRegion
func (mr *MockAWSClientMockRecorder) GetAvailableInstanceTypesInRegion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableInstanceTypesInRegion", reflect.TypeOf((*MockAWSClient)(nil).GetAvailableInstanceTypesInRegion), arg0)
}
