// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spotinst/wave-operator/internal/spot/client (interfaces: OceanClient)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	gomock "github.com/golang/mock/gomock"
	client "github.com/spotinst/wave-operator/internal/spot/client"
	reflect "reflect"
)

// MockOceanClient is a mock of OceanClient interface
type MockOceanClient struct {
	ctrl     *gomock.Controller
	recorder *MockOceanClientMockRecorder
}

// MockOceanClientMockRecorder is the mock recorder for MockOceanClient
type MockOceanClientMockRecorder struct {
	mock *MockOceanClient
}

// NewMockOceanClient creates a new mock instance
func NewMockOceanClient(ctrl *gomock.Controller) *MockOceanClient {
	mock := &MockOceanClient{ctrl: ctrl}
	mock.recorder = &MockOceanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOceanClient) EXPECT() *MockOceanClientMockRecorder {
	return m.recorder
}

// GetAllOceanClusters mocks base method
func (m *MockOceanClient) GetAllOceanClusters() ([]*client.OceanCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOceanClusters")
	ret0, _ := ret[0].([]*client.OceanCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOceanClusters indicates an expected call of GetAllOceanClusters
func (mr *MockOceanClientMockRecorder) GetAllOceanClusters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOceanClusters", reflect.TypeOf((*MockOceanClient)(nil).GetAllOceanClusters))
}
