// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spotinst/wave-operator/internal/config/instances (interfaces: InstanceTypeManager)

// Package mock_instances is a generated GoMock package.
package mock_instances

import (
	gomock "github.com/golang/mock/gomock"
	instances "github.com/spotinst/wave-operator/internal/config/instances"
	reflect "reflect"
)

// MockInstanceTypeManager is a mock of InstanceTypeManager interface
type MockInstanceTypeManager struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceTypeManagerMockRecorder
}

// MockInstanceTypeManagerMockRecorder is the mock recorder for MockInstanceTypeManager
type MockInstanceTypeManagerMockRecorder struct {
	mock *MockInstanceTypeManager
}

// NewMockInstanceTypeManager creates a new mock instance
func NewMockInstanceTypeManager(ctrl *gomock.Controller) *MockInstanceTypeManager {
	mock := &MockInstanceTypeManager{ctrl: ctrl}
	mock.recorder = &MockInstanceTypeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstanceTypeManager) EXPECT() *MockInstanceTypeManagerMockRecorder {
	return m.recorder
}

// GetAllowedInstanceTypes mocks base method
func (m *MockInstanceTypeManager) GetAllowedInstanceTypes() instances.InstanceTypes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedInstanceTypes")
	ret0, _ := ret[0].(instances.InstanceTypes)
	return ret0
}

// GetAllowedInstanceTypes indicates an expected call of GetAllowedInstanceTypes
func (mr *MockInstanceTypeManagerMockRecorder) GetAllowedInstanceTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedInstanceTypes", reflect.TypeOf((*MockInstanceTypeManager)(nil).GetAllowedInstanceTypes))
}

// Start mocks base method
func (m *MockInstanceTypeManager) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockInstanceTypeManagerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockInstanceTypeManager)(nil).Start))
}
