apiVersion: v1
kind: Service
metadata:
  name: {{ include "wave-operator.fullname" . }}-metrics
  labels:
    {{- include "wave-operator.labels" . | nindent 4 }}
  namespace: spot-system
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "wave-operator.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
