// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spotinst/wave-operator/internal/sparkapi/client (interfaces: Client)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	gomock "github.com/golang/mock/gomock"
	client "github.com/spotinst/wave-operator/internal/sparkapi/client"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAllExecutors mocks base method
func (m *MockClient) GetAllExecutors(arg0 string) ([]client.Executor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllExecutors", arg0)
	ret0, _ := ret[0].([]client.Executor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExecutors indicates an expected call of GetAllExecutors
func (mr *MockClientMockRecorder) GetAllExecutors(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExecutors", reflect.TypeOf((*MockClient)(nil).GetAllExecutors), arg0)
}

// GetApplication mocks base method
func (m *MockClient) GetApplication(arg0 string) (*client.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplication", arg0)
	ret0, _ := ret[0].(*client.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplication indicates an expected call of GetApplication
func (mr *MockClientMockRecorder) GetApplication(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplication", reflect.TypeOf((*MockClient)(nil).GetApplication), arg0)
}

// GetEnvironment mocks base method
func (m *MockClient) GetEnvironment(arg0 string) (*client.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", arg0)
	ret0, _ := ret[0].(*client.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment
func (mr *MockClientMockRecorder) GetEnvironment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*MockClient)(nil).GetEnvironment), arg0)
}

// GetStages mocks base method
func (m *MockClient) GetStages(arg0 string) ([]client.Stage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStages", arg0)
	ret0, _ := ret[0].([]client.Stage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStages indicates an expected call of GetStages
func (mr *MockClientMockRecorder) GetStages(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStages", reflect.TypeOf((*MockClient)(nil).GetStages), arg0)
}
